### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by tpeixinho** [steve-chavez/mssqlREST#1]
hi, how can I put the server to listen only in https?

**Comment by steve-chavez** [comment]
Hey @tpeixinho,

This project uses the [spark webserver](https://sparkjava.com/), so you could add the [secure method](https://sparkjava.com/documentation#secure) on the [ApplicationServer class](https://github.com/steve-chavez/mssqlREST/blob/master/src/main/java/mssqlrest/ApplicationServer.java#L51).

Another option, you can put Nginx as a reverse proxy and do https there.

Make sure to read the [limitations](https://github.com/steve-chavez/mssqlREST#limitations) section if you're planning to use this project on production.

**Comment by tpeixinho** [comment]
Thanks @steve-chavez.
It's done.

Now, any thoughts on implementing limits/offsets ?

Thanks.

**Comment by steve-chavez** [comment]
> Now, any thoughts on implementing limits/offsets ?

@tpeixinho Yeah that can be done. The idea would be:

- Add some classes for the limit/offset on Structure.java, here's an example for how this is done for the [order clause](https://github.com/steve-chavez/mssqlREST/blob/master/src/main/java/mssqlrest/Structure.java#L138-L151)
- Parse the limit/offset querystring params in [Parsers.java](https://github.com/steve-chavez/mssqlREST/blob/master/src/main/java/mssqlrest/Parsers.java#L41-L114) and convert that to the previously added classes. This part uses [parsecj](https://github.com/jon-hanson/parsecj) parser combinators.
- Finally add the limit/offset objects in the [QueryBuilder](https://github.com/steve-chavez/mssqlREST/blob/master/src/main/java/mssqlrest/QueryBuilder.java#L23-L47).
- To check it's all working, you can add a test [here](https://github.com/steve-chavez/mssqlREST/blob/master/src/test/java/mssqlrest/QueryTest.java#L84-L88).

I can help with reviewing your PR if you'd like to implement it.
